# -*- coding: utf-8 -*-
"""parsh_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uFB1J1D5S9UW8MY8HCtgln2mEfuTZ8-e
"""

!pip install flask pyngrok

from flask import Flask, request, redirect, render_template_string
from pyngrok import ngrok
import sqlite3, string, random

ngrok.set_auth_token("35WepmSHt4R6D65b6kC5HcXZy76_3DX17a6axgFHCxBNVuLeQ")

conn = sqlite3.connect('url_shortener.db', check_same_thread=False)
cursor = conn.cursor()

cursor.execute('''
CREATE TABLE IF NOT EXISTS urls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    short_code TEXT UNIQUE,
    original_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    access_count INTEGER DEFAULT 0
)
''')
conn.commit()

print("Database initialized successfully!")

def generate_short_code(length=6):
    chars = string.ascii_letters + string.digits
    return ''.join(random.choices(chars, k=length))

app = Flask(__name__)

HTML_TEMPLATE = '''
<!DOCTYPE html>
<html>
<head>
    <title>Parsh’s URL Shortener</title>
    <style>
        body { font-family: Arial; padding: 20px; background: #f2f2f2; }
        .box { background: white; padding: 20px; border-radius: 10px; width: 400px; margin: auto; }
        input, button { width: 100%; padding: 10px; margin-top: 10px; }
        button { background: #007bff; color: white; border: none; border-radius: 5px; }
        .output { margin-top: 20px; padding: 10px; background: #e6ffe6; border-left: 5px solid green; }
    </style>
</head>
<body>
    <div class="box">
        <h2>URL Shortener</h2>
        <form method="POST">
            <input name="url" placeholder="Enter long URL">
            <button type="submit">Shorten URL</button>
        </form>

        {% if short_url %}
        <div class="output">
            <p><b>Short URL:</b> <a href="{{ short_url }}" target="_blank">{{ short_url }}</a></p>
        </div>
        {% endif %}
    </div>
</body>
</html>
'''

@app.route("/", methods=["GET", "POST"])
def home():
    short_url = None

    if request.method == "POST":
        long_url = request.form["url"]
        short_code = generate_short_code()

        cursor.execute(
            "INSERT INTO urls (short_code, original_url) VALUES (?, ?)",
            (short_code, long_url)
        )
        conn.commit()

        short_url = public_url + "/" + short_code

    return render_template_string(HTML_TEMPLATE, short_url=short_url)

@app.route("/<short_code>")
def redirect_url(short_code):
    cursor.execute(
        "SELECT original_url FROM urls WHERE short_code = ?",
        (short_code,)
    )
    result = cursor.fetchone()

    if result:
        return redirect(result[0])
    else:
        return "Invalid short URL!", 404

public_url = ngrok.connect(5000)
print("🔗 Your Live URL Shortener:", public_url)

app.run(port=5000)

from google.colab import files
files.download('url_shortener.db')

















